package com.loyality.jsw.serverrequesthandler;

/**
 * Created by sahil.goyal on 5/3/2018.
 */

public enum ResponseTypes {

    ERRROR, LOGIN,ENQUIRY,FORGOT_PASSWORD,SEND_OTP,REGISTER,PROFILE,PROFILE_BY_ID,TRANSCATION_DETAIL,EDIT_PROFILE,EVENTS,EVENT_DETAIL,APPROVE_FABRICATOR,TRANSACTIONS,RETAILER_TRANSACTIONS,
    RETAILER_TRANSACTIONS_DETAIL,ADD_PRODUCTS,ADD_TRANSACTION_STATUS,ALL_PRODUCTS,PRODUCT_DETAIL,
    PRODUCT_UNITS,STATES,DISTRICT,CITIES,RETAILERS,ADD_RETAILER,SEARCH_FABRICATOR,FABRICATOR_PROFILE,
    FABRICATOR_PURCHASE,SALES_QUERY,SUBMITTM_PROFILE,UPDATE_PURCHASE_VERIFICATION,QUERYRESULT
}
