package com.loyality.jsw.serverrequesthandler;

/**
 * Created by sahil.goyal on 5/3/2018.
 */

public enum ResponseTypes {

    ERRROR, LOGIN,ENQUIRY,FORGOT_PASSWORD,SEND_OTP,REGISTER,PROFILE,TRANSCATION_DETAIL,EDIT_PROFILE,EVENTS,EVENT_DETAIL,TRANSACTIONS,RETAILER_TRANSACTIONS,RETAILER_TRANSACTIONS_DETAIL,ADD_PRODUCTS,ADD_TRANSACTION_STATUS,ALL_PRODUCTS,PRODUCT_DETAIL,PRODUCT_UNITS,STATES,DISTRICT,CITIES,RETAILERS,ADD_RETAILER
}
